# Generated by Django 3.2.3 on 2021-05-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone_no', models.CharField(max_length=10)),
                ('hospital_name', models.CharField(max_length=32)),
                ('hospital_ward_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('province', models.IntegerField(choices=[(1, 'Province 1'), (2, 'Province 2'), (3, 'Bagmati'), (4, 'Gandaki'), (5, 'Lumbini'), (6, 'Karnali'), (7, 'Sudurpaschim')])),
                ('occupation', models.CharField(max_length=34)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('day_of_pcr_positive', models.PositiveIntegerField()),
                ('PCR_CT_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('vaccination_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('prevalent_conditions', models.JSONField()),
                ('stage_of_patient', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=8)),
                ('comorbidity_problems', models.JSONField()),
                ('smoking_status', models.CharField(choices=[('regular', 'Regular Smoker'), ('occasional', 'Occasional smoking habit'), ('quit', 'Has smoking habit but recently quit'), ('never', 'Never had smoking habit')], max_length=10)),
            ],
        ),
    ]
