# Generated by Django 3.2.3 on 2021-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comorbidity_problems',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prevalent_conditions',
            field=models.JSONField(default='{}'),
        ),
    ]
