# Generated by Django 3.2.3 on 2021-05-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210524_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PCR_CT_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='day_of_pcr_positive',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hospital_ward_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.IntegerField(blank=True, choices=[(1, 'Province 1'), (2, 'Province 2'), (3, 'Bagmati'), (4, 'Gandaki'), (5, 'Lumbini'), (6, 'Karnali'), (7, 'Sudurpaschim')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Smoker'), ('occasional', 'Occasional smoking habit'), ('quit', 'Has smoking habit but recently quit'), ('never', 'Never had smoking habit')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stage_of_patient',
            field=models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vaccination_status',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
