# Generated by Django 3.2.3 on 2021-06-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_patients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
