# Generated by Django 3.2.3 on 2021-05-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='sn',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
