# Generated by Django 3.2.3 on 2021-05-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_option_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='sn',
            field=models.IntegerField(unique=True),
        ),
    ]
